$(function () {
    // mainTpl() and example2Tpl are precompiled templates generated by our bundler    
    $('#main').append(mainTpl({ name: "compiled template" }));
    $('#main').append(example2Tpl());
});